### ISSUE TITLE
TraitError: The 'zoom' trait of a CytoscapeWidget instance must be a float

### ISSUE THREAD

**Issue by gqpj** [QuantStack/ipycytoscape#26]
When I run `Test handling in Jupyter.ipynb` (and others) it works but in the log entries on the status bar in JupyterLab 2.0.1 I get many of errors:
```
TraitError                                Traceback (most recent call last)
~/miniconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/miniconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py in set_trait(self, name, value)
   1341                                 (cls.__name__, name))
   1342         else:
-> 1343             getattr(cls, name).set(self, value)
   1344 
   1345     @classmethod

~/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
    557 
    558     def set(self, obj, value):
--> 559         new_value = self._validate(obj, value)
    560         try:
    561             old_value = obj._trait_values[self.name]

~/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    589             return value
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:
    593             value = self._cross_validate(obj, value)

~/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   1974             value = float(value)
   1975         if not isinstance(value, float):
-> 1976             self.error(obj, value)
   1977         return _validate_bounds(self, obj, value)
   1978 

~/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py in error(self, obj, value)
    623             e = "The '%s' trait must be %s, but a value of %r was specified." \
    624                 % (self.name, self.info(), repr_type(value))
--> 625         raise TraitError(e)
    626 
    627     def get_metadata(self, key, default=None):

TraitError: The 'zoom' trait of a CytoscapeWidget instance must be a float, but a value of {'level': 1.3618039761322855} <class 'dict'> was specified.
```

**Comment by marimeireles** [comment]
Okay! Thanks for letting me know of this one!
Will fix it in the next iteration!

**Comment by marimeireles** [comment]
This was fixed by you @ianhi, or am I tripping?

**Comment by ianhi** [comment]
I think this error is the result of dictionary being synced back python as the zoom value. So when zoom stopped being synced this error stopped showing up. But zoom still isn't being synced due to the confusions I had in https://github.com/QuantStack/ipycytoscape/issues/66#issuecomment-625866401

This can probably be closed as no code currently present will induce this error.
